version: '3.9'

services:
  grafana:
    hostname: grafana.devbox
    image: grafana/grafana-oss:latest
    ports:
      - 3000:3000
    networks:
      - web
      - grafana
    labels:
      - traefik.enable=true
      - traefik.docker.network=gateway
      - traefik.http.routers.grafana.rule=Host(`grafana.testnet.web3invest.fr`)
      - traefik.http.routers.grafana.entrypoints=web,websecure
      - traefik.http.routers.grafana.tls.certresolver=w3i_ssl
      - traefik.http.services.grafana.loadbalancer.server.port=80
      - traefik.http.routers.grafana.service=grafana

networks:
  grafana:
  web:
    external:
      name: traefik_webgateway